import type { MemoryFolder } from "./media";

// This file is auto-generated by scripts/sync-memories.mjs
// Generated at: 2026-02-06T07:00:19.933Z
export const generatedMemories: MemoryFolder[] = [
  {
    "id": "bad-poker",
    "title": "Bad Poker",
    "slug": "bad-poker",
    "count": 1,
    "items": [
      {
        "id": "bad-poker-img-5634",
        "title": "IMG 5634",
        "type": "image",
        "src": "/memories/user/bad-poker/img-5634.jpeg",
        "alt": "Bad Poker - IMG 5634"
      }
    ]
  },
  {
    "id": "birthday",
    "title": "Birthday",
    "slug": "birthday",
    "count": 3,
    "items": [
      {
        "id": "birthday-20241206-211449",
        "title": "20241206 211449",
        "type": "image",
        "src": "/memories/user/birthday/20241206-211449.jpeg",
        "alt": "Birthday - 20241206 211449",
        "context": {
          "capturedAt": "2024-12-06T21:14:49.000Z"
        }
      },
      {
        "id": "birthday-img-3793",
        "title": "IMG 3793",
        "type": "video",
        "src": "/memories/user/birthday/img-3793.mov",
        "alt": "Birthday - IMG 3793"
      },
      {
        "id": "birthday-img-3802",
        "title": "IMG 3802",
        "type": "image",
        "src": "/memories/user/birthday/img-3802.jpeg",
        "alt": "Birthday - IMG 3802"
      }
    ]
  },
  {
    "id": "couple-chef",
    "title": "Couple Chef",
    "slug": "couple-chef",
    "count": 1,
    "items": [
      {
        "id": "couple-chef-img-2643",
        "title": "IMG 2643",
        "type": "image",
        "src": "/memories/user/couple-chef/img-2643.jpeg",
        "alt": "Couple Chef - IMG 2643"
      }
    ]
  },
  {
    "id": "cutie-pututie",
    "title": "Cutie Pututie",
    "slug": "cutie-pututie",
    "count": 3,
    "items": [
      {
        "id": "cutie-pututie-20241219-011024",
        "title": "20241219 011024",
        "type": "image",
        "src": "/memories/user/cutie-pututie/20241219-011024.jpeg",
        "alt": "Cutie Pututie - 20241219 011024",
        "context": {
          "capturedAt": "2024-12-19T01:10:24.000Z"
        }
      },
      {
        "id": "cutie-pututie-a96acffb-f528-4737-ad24-5a60161e24ba",
        "title": "a96acffb f528 4737 ad24 5a60161e24ba",
        "type": "image",
        "src": "/memories/user/cutie-pututie/a96acffb-f528-4737-ad24-5a60161e24ba.jpeg",
        "alt": "Cutie Pututie - a96acffb f528 4737 ad24 5a60161e24ba"
      },
      {
        "id": "cutie-pututie-img-3075",
        "title": "IMG 3075",
        "type": "image",
        "src": "/memories/user/cutie-pututie/img-3075.jpeg",
        "alt": "Cutie Pututie - IMG 3075"
      }
    ]
  },
  {
    "id": "escape-room-2025",
    "title": "Escape Room 2025",
    "slug": "escape-room-2025",
    "count": 2,
    "items": [
      {
        "id": "escape-room-2025-img-1604",
        "title": "IMG 1604",
        "type": "image",
        "src": "/memories/user/escape-room-2025/img-1604.jpeg",
        "alt": "Escape Room 2025 - IMG 1604"
      },
      {
        "id": "escape-room-2025-img-1878",
        "title": "IMG 1878",
        "type": "image",
        "src": "/memories/user/escape-room-2025/img-1878.jpeg",
        "alt": "Escape Room 2025 - IMG 1878"
      }
    ]
  },
  {
    "id": "fashion-show",
    "title": "Fashion Show",
    "slug": "fashion-show",
    "count": 4,
    "items": [
      {
        "id": "fashion-show-20241129-125814",
        "title": "20241129 125814",
        "type": "image",
        "src": "/memories/user/fashion-show/20241129-125814.jpeg",
        "alt": "Fashion Show - 20241129 125814",
        "context": {
          "capturedAt": "2024-11-29T12:58:14.000Z"
        }
      },
      {
        "id": "fashion-show-20241129-130407",
        "title": "20241129 130407",
        "type": "image",
        "src": "/memories/user/fashion-show/20241129-130407.jpeg",
        "alt": "Fashion Show - 20241129 130407",
        "context": {
          "capturedAt": "2024-11-29T13:04:07.000Z"
        }
      },
      {
        "id": "fashion-show-20241129-153800",
        "title": "20241129 153800",
        "type": "image",
        "src": "/memories/user/fashion-show/20241129-153800.jpeg",
        "alt": "Fashion Show - 20241129 153800",
        "context": {
          "capturedAt": "2024-11-29T15:38:00.000Z"
        }
      },
      {
        "id": "fashion-show-lp-image",
        "title": "lp image",
        "type": "image",
        "src": "/memories/user/fashion-show/lp-image.jpeg",
        "alt": "Fashion Show - lp image"
      }
    ]
  },
  {
    "id": "first-date",
    "title": "First Date",
    "slug": "first-date",
    "count": 1,
    "items": [
      {
        "id": "first-date-img-20240510-wa0000-1",
        "title": "IMG 20240510 WA0000(1)",
        "type": "image",
        "src": "/memories/user/first-date/img-20240510-wa0000-1.jpeg",
        "alt": "First Date - IMG 20240510 WA0000(1)",
        "context": {
          "capturedAt": "2024-05-10T12:00:00.000Z"
        }
      }
    ]
  },
  {
    "id": "first-time-kyaking",
    "title": "First time kyaking",
    "slug": "first-time-kyaking",
    "count": 2,
    "items": [
      {
        "id": "first-time-kyaking-img-2053",
        "title": "IMG 2053",
        "type": "image",
        "src": "/memories/user/first-time-kyaking/img-2053.jpeg",
        "alt": "First time kyaking - IMG 2053"
      },
      {
        "id": "first-time-kyaking-img-2079",
        "title": "IMG 2079",
        "type": "image",
        "src": "/memories/user/first-time-kyaking/img-2079.jpeg",
        "alt": "First time kyaking - IMG 2079"
      }
    ]
  },
  {
    "id": "formals",
    "title": "Formals",
    "slug": "formals",
    "count": 6,
    "items": [
      {
        "id": "formals-img-0683",
        "title": "IMG 0683",
        "type": "image",
        "src": "/memories/user/formals/img-0683.jpeg",
        "alt": "Formals - IMG 0683"
      },
      {
        "id": "formals-img-0721",
        "title": "IMG 0721",
        "type": "image",
        "src": "/memories/user/formals/img-0721.jpeg",
        "alt": "Formals - IMG 0721"
      },
      {
        "id": "formals-img-1052",
        "title": "IMG 1052",
        "type": "image",
        "src": "/memories/user/formals/img-1052.jpeg",
        "alt": "Formals - IMG 1052"
      },
      {
        "id": "formals-img-20240304-wa0049",
        "title": "IMG 20240304 WA0049",
        "type": "image",
        "src": "/memories/user/formals/img-20240304-wa0049.jpeg",
        "alt": "Formals - IMG 20240304 WA0049",
        "context": {
          "capturedAt": "2024-03-04T12:00:00.000Z"
        }
      },
      {
        "id": "formals-img-20241201-wa0049",
        "title": "IMG 20241201 WA0049",
        "type": "image",
        "src": "/memories/user/formals/img-20241201-wa0049.jpeg",
        "alt": "Formals - IMG 20241201 WA0049",
        "context": {
          "capturedAt": "2024-12-01T12:00:00.000Z"
        }
      },
      {
        "id": "formals-jpeg-image-4af9-9736-09-0",
        "title": "JPEG image 4AF9 9736 09 0",
        "type": "image",
        "src": "/memories/user/formals/jpeg-image-4af9-9736-09-0.jpeg",
        "alt": "Formals - JPEG image 4AF9 9736 09 0"
      }
    ]
  },
  {
    "id": "garba",
    "title": "Garba",
    "slug": "garba",
    "count": 4,
    "items": [
      {
        "id": "garba-img-3069",
        "title": "IMG 3069",
        "type": "image",
        "src": "/memories/user/garba/img-3069.jpeg",
        "alt": "Garba - IMG 3069"
      },
      {
        "id": "garba-img-20241015-wa0157",
        "title": "IMG 20241015 WA0157",
        "type": "image",
        "src": "/memories/user/garba/img-20241015-wa0157.jpeg",
        "alt": "Garba - IMG 20241015 WA0157",
        "context": {
          "capturedAt": "2024-10-15T12:00:00.000Z"
        }
      },
      {
        "id": "garba-img-20241015-wa0205",
        "title": "IMG 20241015 WA0205",
        "type": "image",
        "src": "/memories/user/garba/img-20241015-wa0205.jpeg",
        "alt": "Garba - IMG 20241015 WA0205",
        "context": {
          "capturedAt": "2024-10-15T12:00:00.000Z"
        }
      },
      {
        "id": "garba-img-20241015-wa0209",
        "title": "IMG 20241015 WA0209",
        "type": "image",
        "src": "/memories/user/garba/img-20241015-wa0209.jpeg",
        "alt": "Garba - IMG 20241015 WA0209",
        "context": {
          "capturedAt": "2024-10-15T12:00:00.000Z"
        }
      }
    ]
  },
  {
    "id": "halloween-2025",
    "title": "Halloween 2025",
    "slug": "halloween-2025",
    "count": 3,
    "items": [
      {
        "id": "halloween-2025-img-0574",
        "title": "IMG 0574",
        "type": "image",
        "src": "/memories/user/halloween-2025/img-0574.jpeg",
        "alt": "Halloween 2025 - IMG 0574"
      },
      {
        "id": "halloween-2025-img-3372",
        "title": "IMG 3372",
        "type": "image",
        "src": "/memories/user/halloween-2025/img-3372.jpeg",
        "alt": "Halloween 2025 - IMG 3372"
      },
      {
        "id": "halloween-2025-img-7681",
        "title": "IMG 7681",
        "type": "image",
        "src": "/memories/user/halloween-2025/img-7681.jpeg",
        "alt": "Halloween 2025 - IMG 7681"
      }
    ]
  },
  {
    "id": "how-it-s-going",
    "title": "How It's going",
    "slug": "how-it-s-going",
    "count": 1,
    "items": [
      {
        "id": "how-it-s-going-img-4257",
        "title": "IMG 4257",
        "type": "image",
        "src": "/memories/user/how-it-s-going/img-4257.jpeg",
        "alt": "How It's going - IMG 4257"
      }
    ]
  },
  {
    "id": "late-dine",
    "title": "Late Dine",
    "slug": "late-dine",
    "count": 1,
    "items": [
      {
        "id": "late-dine-img-0302",
        "title": "IMG 0302",
        "type": "image",
        "src": "/memories/user/late-dine/img-0302.jpeg",
        "alt": "Late Dine - IMG 0302"
      }
    ]
  },
  {
    "id": "milk-shake-date",
    "title": "Milk Shake Date",
    "slug": "milk-shake-date",
    "count": 1,
    "items": [
      {
        "id": "milk-shake-date-img-0407",
        "title": "IMG 0407",
        "type": "image",
        "src": "/memories/user/milk-shake-date/img-0407.jpeg",
        "alt": "Milk Shake Date - IMG 0407"
      }
    ]
  },
  {
    "id": "montreal-trips",
    "title": "Montreal Trips",
    "slug": "montreal-trips",
    "count": 9,
    "items": [
      {
        "id": "montreal-trips-img-20240708-173408-448",
        "title": "IMG 20240708 173408 448",
        "type": "image",
        "src": "/memories/user/montreal-trips/img-20240708-173408-448.jpeg",
        "alt": "Montreal Trips - IMG 20240708 173408 448",
        "context": {
          "capturedAt": "2024-07-08T17:34:08.000Z"
        }
      },
      {
        "id": "montreal-trips-img-20240519-wa0005",
        "title": "IMG 20240519 WA0005",
        "type": "image",
        "src": "/memories/user/montreal-trips/img-20240519-wa0005.jpeg",
        "alt": "Montreal Trips - IMG 20240519 WA0005",
        "context": {
          "capturedAt": "2024-05-19T12:00:00.000Z"
        }
      },
      {
        "id": "montreal-trips-img-20240519-wa0006",
        "title": "IMG 20240519 WA0006",
        "type": "image",
        "src": "/memories/user/montreal-trips/img-20240519-wa0006.jpeg",
        "alt": "Montreal Trips - IMG 20240519 WA0006",
        "context": {
          "capturedAt": "2024-05-19T12:00:00.000Z"
        }
      },
      {
        "id": "montreal-trips-img-20240519-wa0019",
        "title": "IMG 20240519 WA0019",
        "type": "image",
        "src": "/memories/user/montreal-trips/img-20240519-wa0019.jpeg",
        "alt": "Montreal Trips - IMG 20240519 WA0019",
        "context": {
          "capturedAt": "2024-05-19T12:00:00.000Z"
        }
      },
      {
        "id": "montreal-trips-img-20240707-wa0488",
        "title": "IMG 20240707 WA0488",
        "type": "image",
        "src": "/memories/user/montreal-trips/img-20240707-wa0488.jpeg",
        "alt": "Montreal Trips - IMG 20240707 WA0488",
        "context": {
          "capturedAt": "2024-07-07T12:00:00.000Z"
        }
      },
      {
        "id": "montreal-trips-img-20240707-wa0966",
        "title": "IMG 20240707 WA0966",
        "type": "image",
        "src": "/memories/user/montreal-trips/img-20240707-wa0966.jpeg",
        "alt": "Montreal Trips - IMG 20240707 WA0966",
        "context": {
          "capturedAt": "2024-07-07T12:00:00.000Z"
        }
      },
      {
        "id": "montreal-trips-img-20240707-wa1056",
        "title": "IMG 20240707 WA1056",
        "type": "image",
        "src": "/memories/user/montreal-trips/img-20240707-wa1056.jpeg",
        "alt": "Montreal Trips - IMG 20240707 WA1056",
        "context": {
          "capturedAt": "2024-07-07T12:00:00.000Z"
        }
      },
      {
        "id": "montreal-trips-img-20240708-wa0038",
        "title": "IMG 20240708 WA0038",
        "type": "image",
        "src": "/memories/user/montreal-trips/img-20240708-wa0038.jpeg",
        "alt": "Montreal Trips - IMG 20240708 WA0038",
        "context": {
          "capturedAt": "2024-07-08T12:00:00.000Z"
        }
      },
      {
        "id": "montreal-trips-img-20240708-wa0205",
        "title": "IMG 20240708 WA0205",
        "type": "image",
        "src": "/memories/user/montreal-trips/img-20240708-wa0205.jpeg",
        "alt": "Montreal Trips - IMG 20240708 WA0205",
        "context": {
          "capturedAt": "2024-07-08T12:00:00.000Z"
        }
      }
    ]
  },
  {
    "id": "my-queen",
    "title": "My Queen",
    "slug": "my-queen",
    "count": 1,
    "items": [
      {
        "id": "my-queen-20241208-181129",
        "title": "20241208 181129",
        "type": "image",
        "src": "/memories/user/my-queen/20241208-181129.jpeg",
        "alt": "My Queen - 20241208 181129",
        "context": {
          "capturedAt": "2024-12-08T18:11:29.000Z"
        }
      }
    ]
  },
  {
    "id": "our-first-church-visit-together",
    "title": "Our First Church Visit together",
    "slug": "our-first-church-visit-together",
    "count": 3,
    "items": [
      {
        "id": "our-first-church-visit-together-img-20240707-wa0736",
        "title": "IMG 20240707 WA0736",
        "type": "image",
        "src": "/memories/user/our-first-church-visit-together/img-20240707-wa0736.jpeg",
        "alt": "Our First Church Visit together - IMG 20240707 WA0736",
        "context": {
          "capturedAt": "2024-07-07T12:00:00.000Z"
        }
      },
      {
        "id": "our-first-church-visit-together-img-20240707-wa0836",
        "title": "IMG 20240707 WA0836",
        "type": "image",
        "src": "/memories/user/our-first-church-visit-together/img-20240707-wa0836.jpeg",
        "alt": "Our First Church Visit together - IMG 20240707 WA0836",
        "context": {
          "capturedAt": "2024-07-07T12:00:00.000Z"
        }
      },
      {
        "id": "our-first-church-visit-together-img-20240707-wa0870",
        "title": "IMG 20240707 WA0870",
        "type": "image",
        "src": "/memories/user/our-first-church-visit-together/img-20240707-wa0870.jpeg",
        "alt": "Our First Church Visit together - IMG 20240707 WA0870",
        "context": {
          "capturedAt": "2024-07-07T12:00:00.000Z"
        }
      }
    ]
  },
  {
    "id": "perfect-food",
    "title": "Perfect Food",
    "slug": "perfect-food",
    "count": 1,
    "items": [
      {
        "id": "perfect-food-img-1597",
        "title": "IMG 1597",
        "type": "image",
        "src": "/memories/user/perfect-food/img-1597.jpeg",
        "alt": "Perfect Food - IMG 1597"
      }
    ]
  },
  {
    "id": "reveal-to-the-world",
    "title": "Reveal To the World",
    "slug": "reveal-to-the-world",
    "count": 1,
    "items": [
      {
        "id": "reveal-to-the-world-24f16359e9915cf09d77b09d21cf75ba",
        "title": "24f16359e9915cf09d77b09d21cf75ba",
        "type": "image",
        "src": "/memories/user/reveal-to-the-world/24f16359e9915cf09d77b09d21cf75ba.jpeg",
        "alt": "Reveal To the World - 24f16359e9915cf09d77b09d21cf75ba"
      }
    ]
  },
  {
    "id": "right-flowers",
    "title": "Right Flowers",
    "slug": "right-flowers",
    "count": 1,
    "items": [
      {
        "id": "right-flowers-img-1512",
        "title": "IMG 1512",
        "type": "image",
        "src": "/memories/user/right-flowers/img-1512.jpeg",
        "alt": "Right Flowers - IMG 1512"
      }
    ]
  },
  {
    "id": "same-same-but-different",
    "title": "Same Same But Different",
    "slug": "same-same-but-different",
    "count": 1,
    "items": [
      {
        "id": "same-same-but-different-20231209-192152",
        "title": "20231209 192152",
        "type": "image",
        "src": "/memories/user/same-same-but-different/20231209-192152.jpeg",
        "alt": "Same Same But Different  - 20231209 192152",
        "context": {
          "capturedAt": "2023-12-09T19:21:52.000Z"
        }
      }
    ]
  },
  {
    "id": "slomo-looking-cute-baby",
    "title": "Slomo looking Cute Baby",
    "slug": "slomo-looking-cute-baby",
    "count": 1,
    "items": [
      {
        "id": "slomo-looking-cute-baby-img-3066",
        "title": "IMG 3066",
        "type": "video",
        "src": "/memories/user/slomo-looking-cute-baby/img-3066.mov",
        "alt": "Slomo looking Cute Baby - IMG 3066"
      }
    ]
  },
  {
    "id": "what-would-i-do-without-you-bloody-marry-incident",
    "title": "What would I do without you, Bloody marry incident",
    "slug": "what-would-i-do-without-you-bloody-marry-incident",
    "count": 1,
    "items": [
      {
        "id": "what-would-i-do-without-you-bloody-marry-incident-img-20240707-wa0924",
        "title": "IMG 20240707 WA0924",
        "type": "image",
        "src": "/memories/user/what-would-i-do-without-you-bloody-marry-incident/img-20240707-wa0924.jpeg",
        "alt": "What would I do without you, Bloody marry incident - IMG 20240707 WA0924",
        "context": {
          "capturedAt": "2024-07-07T12:00:00.000Z"
        }
      }
    ]
  },
  {
    "id": "when-shona-chose-restaurent",
    "title": "When Shona chose restaurent",
    "slug": "when-shona-chose-restaurent",
    "count": 1,
    "items": [
      {
        "id": "when-shona-chose-restaurent-img-3542",
        "title": "IMG 3542",
        "type": "image",
        "src": "/memories/user/when-shona-chose-restaurent/img-3542.jpeg",
        "alt": "When Shona chose restaurent - IMG 3542"
      }
    ]
  },
  {
    "id": "where-i-fell",
    "title": "Where I fell",
    "slug": "where-i-fell",
    "count": 8,
    "items": [
      {
        "id": "where-i-fell-20231209-205502",
        "title": "20231209 205502",
        "type": "image",
        "src": "/memories/user/where-i-fell/20231209-205502.jpeg",
        "alt": "Where I fell - 20231209 205502",
        "context": {
          "capturedAt": "2023-12-09T20:55:02.000Z"
        }
      },
      {
        "id": "where-i-fell-20240207-212950",
        "title": "20240207 212950",
        "type": "image",
        "src": "/memories/user/where-i-fell/20240207-212950.jpeg",
        "alt": "Where I fell - 20240207 212950",
        "context": {
          "capturedAt": "2024-02-07T21:29:50.000Z"
        }
      },
      {
        "id": "where-i-fell-20240207-221604",
        "title": "20240207 221604",
        "type": "image",
        "src": "/memories/user/where-i-fell/20240207-221604.jpeg",
        "alt": "Where I fell - 20240207 221604",
        "context": {
          "capturedAt": "2024-02-07T22:16:04.000Z"
        }
      },
      {
        "id": "where-i-fell-20240210-023446",
        "title": "20240210 023446",
        "type": "image",
        "src": "/memories/user/where-i-fell/20240210-023446.jpeg",
        "alt": "Where I fell - 20240210 023446",
        "context": {
          "capturedAt": "2024-02-10T02:34:46.000Z"
        }
      },
      {
        "id": "where-i-fell-a69abd64ea284d8701f1eb2dbc70aac9",
        "title": "a69abd64ea284d8701f1eb2dbc70aac9",
        "type": "image",
        "src": "/memories/user/where-i-fell/a69abd64ea284d8701f1eb2dbc70aac9.jpeg",
        "alt": "Where I fell - a69abd64ea284d8701f1eb2dbc70aac9"
      },
      {
        "id": "where-i-fell-bereal-2024-04-27-1213",
        "title": "bereal 2024 04 27 1213",
        "type": "image",
        "src": "/memories/user/where-i-fell/bereal-2024-04-27-1213.jpeg",
        "alt": "Where I fell - bereal 2024 04 27 1213",
        "context": {
          "capturedAt": "2024-04-27T12:13:00.000Z"
        }
      },
      {
        "id": "where-i-fell-img-6118",
        "title": "IMG 6118",
        "type": "image",
        "src": "/memories/user/where-i-fell/img-6118.jpeg",
        "alt": "Where I fell - IMG 6118"
      },
      {
        "id": "where-i-fell-img-20240428-183733-021",
        "title": "IMG 20240428 183733 021",
        "type": "image",
        "src": "/memories/user/where-i-fell/img-20240428-183733-021.jpeg",
        "alt": "Where I fell - IMG 20240428 183733 021",
        "context": {
          "capturedAt": "2024-04-28T18:37:33.000Z"
        }
      }
    ]
  },
  {
    "id": "where-it-all-started",
    "title": "Where It All Started",
    "slug": "where-it-all-started",
    "count": 1,
    "items": [
      {
        "id": "where-it-all-started-img-6458",
        "title": "IMG 6458",
        "type": "image",
        "src": "/memories/user/where-it-all-started/img-6458.jpeg",
        "alt": "Where It All Started - IMG 6458"
      }
    ]
  },
  {
    "id": "winter-wonderland",
    "title": "Winter Wonderland",
    "slug": "winter-wonderland",
    "count": 1,
    "items": [
      {
        "id": "winter-wonderland-20241124-201543",
        "title": "20241124 201543",
        "type": "image",
        "src": "/memories/user/winter-wonderland/20241124-201543.jpeg",
        "alt": "Winter Wonderland - 20241124 201543",
        "context": {
          "capturedAt": "2024-11-24T20:15:43.000Z"
        }
      }
    ]
  },
  {
    "id": "your-dewana",
    "title": "Your dewana",
    "slug": "your-dewana",
    "count": 1,
    "items": [
      {
        "id": "your-dewana-img-0665",
        "title": "IMG 0665",
        "type": "image",
        "src": "/memories/user/your-dewana/img-0665.jpeg",
        "alt": "Your dewana - IMG 0665"
      }
    ]
  }
];
